### ISSUE TITLE
Problem in Chrome

### ISSUE THREAD

**Issue by vovanmix** [atomicpages/skeleton-sass#17] opened 2015-03-15 07:38 UTC
Hi!
I have a problem, only in Chrome, that in several consequent page refresh font-size and line-height are different. You can see it at http://skeleton.vprogrammer.com/
sometimes line-height: 41.5999984741211px,   font-size: 22.3999996185303px;
and sometimes line-height: 26px; font-size: 14px;
Tell me please why does it act so strangely and what can I do to fix it?
Thank you.

**Comment by atomicpages** [comment] 2015-03-15 16:39
Are you compiling your `.sass` on-the-fly? It doesn't seem like it. Chrome should be rendering whatever you have in your CSS file. I tried to replicate the problem but I didn't see it happening for me using Chrome 42 and I also checked it on Safari and Firefox as well without seeing the issue. Is there a particular element this is happening on?

**Comment by vovanmix** [comment] 2015-03-16 08:46
I .sass compile it once before publishing the project.
The problem shows up when I refresh page about 10 times in a row, and I see all fonts and line height 2 times bigger than usual. The wrong styles are applied to html element. It has font-size: 62.5%, and I think that it sometimes renders in a wrong way.
I use Chrome 41.0.2272.89 for mac.
There is no such error in FF and others.
Here is two screenshots:
![screen shot 2015-03-16 at 01 45 35](https://cloud.githubusercontent.com/assets/7279514/6662911/2c75dc7e-cb7e-11e4-982d-553665817f92.png)
![screen shot 2015-03-16 at 01 45 40](https://cloud.githubusercontent.com/assets/7279514/6662912/2c763994-cb7e-11e4-832a-ac28ee184c4c.png)

**Comment by atomicpages** [comment] 2015-03-16 16:02
I'm unable to reproduce this problem on OS X, Windows, or Linux (Ubuntu 14.04, CentOS 6/7) using Chrome 41.0.x. Is there a difference in CSS being applied when you view the style sheet in the DOM inspector? I'm hesitant to say this is an issue with your Chrome installation but it seems like that might be the case! Maybe try uninstalling/reinstalling Chrome?

**Comment by vovanmix** [comment] 2015-03-16 21:52
Just tried on another mac, the problem still exists there. Do you watching it at my example at http://skeleton.vprogrammer.com/?
In DOM inspector I see `font-size: 62.5%` for `html` element. And when I go to computed styles, there is sometimes `font-size: 14px;` and sometimes `font-size: 22.3999996185303px;`. For the same window size. Every ~10th refresh in a row.
So I think that the problem is while calculating actual font size.
And the other thing - if it comes with too big font-size, and I try to scale the window width to 300px and then back to 1200px, font-size becomes normal.

**Comment by atomicpages** [comment] 2015-03-16 22:04
What if you disabled rem font units in favor of pixels? Also, what version of OS X?

**Comment by vovanmix** [comment] 2015-03-17 00:37
Pixels will work, problem is with rem.
Os X 10.10.2

**Comment by atomicpages** [comment] 2015-03-17 00:48
How about em and percent units? I'm asking because I want to try and replicate exactly what you're experiencing! Thanks for your patience!

**Comment by vovanmix** [comment] 2015-03-17 01:18
em and % are also act strangely, different computed value every time.

**Comment by atomicpages** [comment] 2015-03-17 21:08
@vovanmix I'm having a really difficult time debugging this. Not matter than machine I use or who I ask, no one can reproduce the issue. The problem doesn't seem to be with Skeleton Sass and the use of a px fallback is [definitely used in the wild](http://html5please.com/#fallback).

Secondly, I tested the resizing issue and everything checked out for me using Chrome/Firefox on OS X, Windows 7, Windows 8.1, Ubuntu 14.x, and CentOS 7. I checked Safari on OS X and everything worked fine. I did some more testing with IE 11, 10, and 9. 11 worked perfectly and there are a few lingering issues with 10 and 9 that I have yet to address (that might be addressed in 2.5). I highly recommend reinstalling Chrome (just drop it into your applications folder and replace all files). It might also be worthwhile to flush your browser cache from the "beginning of time" after you replace the old files.

Has anyone else seen an issue like this before? I've done some searching around on the web and I haven't seen anything.

**Comment by vovanmix** [comment] 2015-03-18 08:56
Tried to reinstall and clean, still have the problem. Sometimes it appears every 20 refresh, but it's still there.
Now I have only 2 computers to make a test, I'll try to find another and will write you if there will be the same problem.
Thank you!

**Closed** 2015-03-20 18:36 UTC
